/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ThreadsIndexRouteImport } from './routes/threads.index'
import { Route as ThreadsIdRouteImport } from './routes/threads.$id'
import { Route as ThreadsIdEditRouteImport } from './routes/threads.$id_.edit'
import { Route as ThreadsIdPostsPostIdEditRouteImport } from './routes/threads.$id_.posts.$postId.edit'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ThreadsIndexRoute = ThreadsIndexRouteImport.update({
  id: '/threads/',
  path: '/threads/',
  getParentRoute: () => rootRouteImport,
} as any)
const ThreadsIdRoute = ThreadsIdRouteImport.update({
  id: '/threads/$id',
  path: '/threads/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ThreadsIdEditRoute = ThreadsIdEditRouteImport.update({
  id: '/threads/$id_/edit',
  path: '/threads/$id/edit',
  getParentRoute: () => rootRouteImport,
} as any)
const ThreadsIdPostsPostIdEditRoute =
  ThreadsIdPostsPostIdEditRouteImport.update({
    id: '/threads/$id_/posts/$postId/edit',
    path: '/threads/$id/posts/$postId/edit',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/threads/$id': typeof ThreadsIdRoute
  '/threads/': typeof ThreadsIndexRoute
  '/threads/$id/edit': typeof ThreadsIdEditRoute
  '/threads/$id/posts/$postId/edit': typeof ThreadsIdPostsPostIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/threads/$id': typeof ThreadsIdRoute
  '/threads': typeof ThreadsIndexRoute
  '/threads/$id/edit': typeof ThreadsIdEditRoute
  '/threads/$id/posts/$postId/edit': typeof ThreadsIdPostsPostIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/threads/$id': typeof ThreadsIdRoute
  '/threads/': typeof ThreadsIndexRoute
  '/threads/$id_/edit': typeof ThreadsIdEditRoute
  '/threads/$id_/posts/$postId/edit': typeof ThreadsIdPostsPostIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/threads/$id'
    | '/threads/'
    | '/threads/$id/edit'
    | '/threads/$id/posts/$postId/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/threads/$id'
    | '/threads'
    | '/threads/$id/edit'
    | '/threads/$id/posts/$postId/edit'
  id:
    | '__root__'
    | '/'
    | '/threads/$id'
    | '/threads/'
    | '/threads/$id_/edit'
    | '/threads/$id_/posts/$postId/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ThreadsIdRoute: typeof ThreadsIdRoute
  ThreadsIndexRoute: typeof ThreadsIndexRoute
  ThreadsIdEditRoute: typeof ThreadsIdEditRoute
  ThreadsIdPostsPostIdEditRoute: typeof ThreadsIdPostsPostIdEditRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/threads/': {
      id: '/threads/'
      path: '/threads'
      fullPath: '/threads/'
      preLoaderRoute: typeof ThreadsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/threads/$id': {
      id: '/threads/$id'
      path: '/threads/$id'
      fullPath: '/threads/$id'
      preLoaderRoute: typeof ThreadsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/threads/$id_/edit': {
      id: '/threads/$id_/edit'
      path: '/threads/$id/edit'
      fullPath: '/threads/$id/edit'
      preLoaderRoute: typeof ThreadsIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/threads/$id_/posts/$postId/edit': {
      id: '/threads/$id_/posts/$postId/edit'
      path: '/threads/$id/posts/$postId/edit'
      fullPath: '/threads/$id/posts/$postId/edit'
      preLoaderRoute: typeof ThreadsIdPostsPostIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ThreadsIdRoute: ThreadsIdRoute,
  ThreadsIndexRoute: ThreadsIndexRoute,
  ThreadsIdEditRoute: ThreadsIdEditRoute,
  ThreadsIdPostsPostIdEditRoute: ThreadsIdPostsPostIdEditRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
